INSERT INTO core.jobs (
    job_id,
    job_title,
    description,
    redirect_url,
    adref,
    company_name,
    company_area,
    location_name,
    location_area,
    category_tag,
    category_label,
    contract_type,
    contract_time,
    salary_min,
    salary_max,
    salary_is_predicted,
    created,
    latitude,
    longitude
) SELECT
    job_id,
    job_title,
    description,
    redirect_url,
    adref,
    company_name,
    company_area,
    location_name,
    location_area,
    category_tag,
    category_label,
    contract_type,
    contract_time,
    salary_min,
    salary_max,
    salary_is_predicted,
    created,
    latitude,
    longitude
 FROM stg.adzuna_jobs_typed
    ON CONFLICT (job_id)
    DO UPDATE SET
        job_title = EXCLUDED.job_title,
        description = EXCLUDED.description,
        redirect_url = EXCLUDED.redirect_url,
        adref = EXCLUDED.adref,
        company_name = EXCLUDED.company_name,
        company_area = EXCLUDED.company_area,
        location_name = EXCLUDED.location_name,
        location_area = EXCLUDED.location_area,
        category_tag = EXCLUDED.category_tag,
        category_label = EXCLUDED.category_label,
        contract_type = EXCLUDED.contract_type,
        contract_time = EXCLUDED.contract_time,
        salary_min = EXCLUDED.salary_min,
        salary_max = EXCLUDED.salary_max,
        salary_is_predicted = EXCLUDED.salary_is_predicted,
        created = EXCLUDED.created,
        latitude = EXCLUDED.latitude,
        longitude = EXCLUDED.longitude;